# backend/shared/models.py
from datetime import datetime
from typing import Optional, List, Dict, Any, Literal, Union
from pydantic import BaseModel, Field
from .enums import TradeAction, OrderType, OrderStatus, RiskStatus


class FibonacciLevel(BaseModel):
    level: float   # e.g. 0.382
    price: float   # actual price at this level


class MarketSummary(BaseModel):
    """
    Rich structured output from the AI market summary pipeline.
    Combines quantitative calculations with LLM-generated narrative.
    """
    # === Core ===
    symbol: str = "VN30F1M"
    generated_at: datetime = Field(default_factory=datetime.now)
    regime: Literal["TRENDING_UP", "TRENDING_DOWN", "CHOPPY", "VOLATILE", "CLOSED"] = "CHOPPY"
    bias: Literal["BULLISH", "BEARISH", "NEUTRAL"] = "NEUTRAL"
    confidence: int = 50  # 0-100

    # === Price Context ===
    current_price: float = 0.0
    price_change: float = 0.0
    price_change_pct: float = 0.0
    period_high: float = 0.0
    period_low: float = 0.0

    # === Trend ===
    trend_short: str = "NEUTRAL"
    trend_medium: str = "NEUTRAL"
    momentum: Literal["STRONG", "MODERATE", "WEAK", "FLAT"] = "WEAK"

    # === Key Levels ===
    supports: List[float] = Field(default_factory=list)
    resistances: List[float] = Field(default_factory=list)

    # === Fibonacci ===
    swing_high: float = 0.0
    swing_low: float = 0.0
    fibonacci_levels: List[FibonacciLevel] = Field(default_factory=list)
    nearest_fib_zone: str = ""

    # === Indicators Snapshot ===
    rsi: float = 0.0
    macd_hist: float = 0.0
    adx: float = 0.0
    atr: float = 0.0
    volume_ratio: float = 1.0  # current vol / avg vol (20)
    ema9: float = 0.0
    ema21: float = 0.0
    price_vs_ema9: Literal["ABOVE", "BELOW", "AT"] = "AT"
    price_vs_ema21: Literal["ABOVE", "BELOW", "AT"] = "AT"
    supertrend_dir: int = 0  # 1 = bullish, -1 = bearish

    # === AI Narrative ===
    one_liner: str = ""
    scenario_bullish: str = ""
    scenario_bearish: str = ""
    risk_note: str = ""
    ai_source: str = ""

    # === Data Quality ===
    data_quality: Literal["full", "partial", "price_action_only"] = "full"
    missing_indicators: List[str] = Field(default_factory=list)
    bars_used: int = 0


class EntryZone(BaseModel):
    min_price: float
    max_price: float

class SignalRecommendation(BaseModel):
    """
    Structured trading recommendation generated by the new Rule Engine.
    Combines hard Technical Math (Calculated targets, stops, zones) 
    with AI's narrative reasoning.
    """
    signal_id: str = Field(default_factory=lambda: datetime.now().strftime("REC-%Y%m%d%H%M%S%f"))
    symbol: str
    timeframe: str = "15m"
    recommendation: Literal["BUY", "SELL", "HOLD", "WAIT"] = "WAIT"
    bias: Literal["BULLISH", "BEARISH", "NEUTRAL"] = "NEUTRAL"
    mtf_bias_15m: str = "NEUTRAL"
    mtf_setup_5m: str = "NEUTRAL"
    mtf_timing_1m: str = "NEUTRAL"
    confidence: float = 0.0
    
    # Technical Levels (Hard Math)
    current_price: float
    entry_zone: Optional[EntryZone] = None
    stop_loss: Optional[float] = None
    take_profit_targets: List[float] = Field(default_factory=list)
    exit_strategy: str = ""
    trailing_stop_timeframe: str = ""
    trailing_stop_atr_period: int = 14
    trailing_stop_atr_multiplier: float = 0.0
    trailing_stop_atr: Optional[float] = None
    trailing_stop_offset: Optional[float] = None
    
    # Context
    supports: List[float] = Field(default_factory=list)
    resistances: List[float] = Field(default_factory=list)
    nearest_fib_zone: str = ""
    trend_short: str = "NEUTRAL"
    trend_medium: str = "NEUTRAL"
    momentum: str = "WEAK"
    risk_reward_estimate: float = 0.0
    
    # AI Reasoning (Narrative)
    reasoning: List[str] = Field(default_factory=list)
    risk_note: str = ""
    
    # Meta
    data_status: Literal["live", "stale"] = "live"
    generated_at: datetime = Field(default_factory=datetime.now)

class MarketBar(BaseModel):
    symbol: str
    timeframe: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    source: Literal["dnse", "vnstock", "tcbs", "mock"] = "dnse"

class LiveMarketSnapshot(BaseModel):
    symbol: str
    price: float
    bid: Optional[float] = None
    ask: Optional[float] = None
    volume: Optional[int] = None
    timestamp: datetime = Field(default_factory=datetime.now)
    source_timestamp: Optional[datetime] = None
    is_stale: bool = False

class FeatureVector(BaseModel):
    symbol: str
    timestamp: datetime
    features: Dict[str, float]
    metadata: Dict[str, Any] = Field(default_factory=dict)

class TradeIntent(BaseModel):
    signal_id: str = Field(default_factory=lambda: datetime.now().strftime("%Y%m%d%H%M%S%f"))
    strategy_name: str
    symbol: str
    action: TradeAction
    confidence: float
    entry_type: OrderType = OrderType.MARKET
    entry_price: Optional[float] = None
    qty: int = 0
    stop_loss: Optional[float] = None
    take_profit: Optional[Union[float, List[float]]] = None
    reason: str
    timeframe: str
    paper_mode: bool = True
    risk_note: Optional[str] = None
    ai_source: str = ""
    created_at: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(default_factory=dict)

class RiskResult(BaseModel):
    is_approved: bool
    status: RiskStatus
    reason: Optional[str] = None
    adjusted_qty: Optional[int] = None
    timestamp: datetime = Field(default_factory=datetime.now)

class OrderRequestNormalized(BaseModel):
    symbol: str
    action: TradeAction
    qty: int
    price: Optional[float] = None
    order_type: OrderType = OrderType.MARKET
    paper_mode: bool = True
    client_order_id: Optional[str] = None

class OrderStateNormalized(BaseModel):
    order_id: str
    status: OrderStatus
    filled_qty: int = 0
    avg_price: Optional[float] = None
    last_filled_price: Optional[float] = None
    message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)

class FillEvent(BaseModel):
    order_id: str
    symbol: str
    filled_qty: int
    price: float
    timestamp: datetime = Field(default_factory=datetime.now)

class RejectEvent(BaseModel):
    order_id: Optional[str] = None
    reason: str
    code: str = "UNKNOWN"
    timestamp: datetime = Field(default_factory=datetime.now)

class OrderReceipt(BaseModel):
    order_id: str
    client_order_id: Optional[str] = None
    symbol: str
    action: TradeAction
    qty: int
    price: Optional[float] = None
    filled_price: Optional[float] = None
    status: OrderStatus
    timestamp: datetime = Field(default_factory=datetime.now)
    paper_mode: bool = True
    message: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

class SystemEvent(BaseModel):
    event_type: str # e.g., "WS_RECONNECT", "RISK_REJECT", "STRATEGY_SIGNAL", "KILL_SWITCH"
    level: str = "INFO" # INFO, WARNING, ERROR, CRITICAL
    message: str
    details: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)
    broadcast: bool = True # Send to Telegram/WS

class ExecutionEvent(BaseModel):
    """Event specifically for order life-cycle tracking (SoT: TCBS WS)"""
    event_id: str = Field(default_factory=lambda: datetime.now().strftime("%Y%m%d%H%M%S%f"))
    order_id: str
    symbol: str
    event_type: Literal["SENT", "ACK", "FILLED", "REJECTED", "CANCELLED", "AMENDED"]
    price: Optional[float] = None
    qty: int = 0
    message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(default_factory=dict)
